services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: UTC # change if necessary eg) Australia/Melbourne
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dashboard"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 3s
